stages:
- stage: deploy_infra 
  displayName: Deploy Infrastructure
  jobs:
  - job: deploy_infra
    displayName: Deploy SWA and Update DNS
    variables:
      - name: rgName
        value: jio-blog-rg
      - name: swaName
        value: jio-blog-swa
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Create Static Web App
      inputs:
        connectedServiceName: personal
        action: Create Or Update Resource Group
        resourceGroupName: ${{ variables.rgName }}
        location: westeurope
        templateLocation: Linked artifact
        csmFile: .azuredevops/infra/website.bicep
        overrideParameters: -customDomains ["www.janssen.io"] -name "${{ variables.swaName}}"
        deploymentMode: Incremental
        deploymentOutputs: websiteOutput

    - pwsh: |
        $outputs = '$(websiteOutput)' | ConvertFrom-Json
        $outputs.PSObject.Properties | ForEach-Object {
          Write-Output "##vso[task.setvariable variable=$_.Name]$_.Value.value"
        }
      displayName: Capture ARM output as variables

    # TODO: setup DNS

    - task: AzureCLI@2
      displayName: Get API key
      inputs:
        azureSubscription: personal
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          $secrets = az staticwebapp secrets list -n "${{ variables.swaName}}" -g "${{ variables.rgName }}" | ConvertFrom-Json
          Write-Output "##vso[task.setvariable variable=apiKey]$secrets.properties.apiKey"

    - pwsh: |
        echo $(apiKey)

    - task: AzureStaticWebApp@0
      inputs:
        app_location: "."
        # api_location: api
        azure_static_web_apps_api_token: $(apiKey)
                